apiVersion: v1
kind: ConfigMap
metadata:
  name: scenarios-config
data:
  scenarios.yaml: |
    application_outage:                                  # Scenario to create an outage of an application by blocking traffic
      duration: 600                                      # Duration in seconds after which the routes will be accessible
      namespace: pitc-rhe-kraken                         # Namespace to target - all application routes will go inaccessible if pod selector is empty
      pod_selector: {app: example-web-go}                # Pods to target
      block: [Ingress, Egress]   