{{- range .Values.amq.addresses }}
apiVersion: broker.amq.io/v2alpha3
kind: ActiveMQArtemisAddress
metadata:
  name: {{ .name }}
spec:
  addressName: {{ .addressName }}
  queueName: {{ .queueName }}
  routingType: {{ .routingType }}
---
{{- end }}    