apiVersion: broker.amq.io/v2alpha5
kind: ActiveMQArtemis
metadata:
  name: {{ include "amq-broker.fullname" . }}
  labels:
    {{- include "amq-broker.labels" . | nindent 4 }}
spec:
  {{- with .Values.amq.broker.acceptors }}
  acceptors:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  addressSettings: {}
  console:
    expose: {{ .Values.amq.broker.console.expose }}
  deploymentPlan:
    enableMetricsPlugin: true
    extraMounts: {}
    image: placeholder
    journalType: nio
    livenessProbe: {}
    messageMigration: true
    persistenceEnabled: true
    podSecurity: {}
    readinessProbe: {}
    requireLogin: true
    {{- with .Values.amq.broker.resources }}
    resources:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    size: {{ .Values.amq.broker.size }}
    storage:
      size: {{ .Values.amq.broker.storage.size }}
  upgrades:
    enabled: false
    minor: false
