apiVersion: broker.amq.io/v2alpha5
kind: ActiveMQArtemis
metadata:
  name: artemis-cluster
spec:
  acceptors:
    - name: amqp
      port: 61616
      protocols: amqp
      expose: true
  addressSettings: {}
  console:
    expose: true
  deploymentPlan:
    enableMetricsPlugin: true
    extraMounts: {}
    image: placeholder
    journalType: nio
    livenessProbe: {}
    messageMigration: true
    persistenceEnabled: true
    podSecurity: {}
    readinessProbe: {}
    requireLogin: true
    resources:
      limits:
        cpu: "2"
        memory: 3Gi
      requests:
        cpu: 100m
        memory: 750Mi
    size: 2
    storage:
      size: 1Gi
  upgrades:
    enabled: false
    minor: false
