apiVersion: broker.amq.io/v1alpha1
kind: ActiveMQArtemisSecurity
metadata:
  name: sender-receiver
spec:
  loginModules:
    propertiesLoginModules:
    - name: prop-module-users
      users:
      - name: amqsender
        password: changeme
        roles:
        - sender
      - name: amqreceiver
        password: changeme
        roles:
        - receiver
  securityDomains:
    brokerDomain:
      loginModules:
      - flag: sufficient
        name: prop-module-users
      name: activemq
  securitySettings:
    broker:
    - match: 'words'
      permissions:
      - operationType: send
        roles:
        - sender
      - operationType: createAddress
        roles:
        - sender
      - operationType: createDurableQueue
        roles:
        - sender
      - operationType: consume
        roles:
        - receiver
