apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: consumer1
  name: consumer1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: consumer1
    spec:
      containers:
        - env:
            - name: QUARKUS_LOG_LEVEL
              value: INFO
            - name: AMQP_HOST
              value: amqbroker-amq-broker-hdls-svc
            - name: AMQP_PORT
              value: "61616"
            - name: AMQP_USERNAME
              value: amqsender
            - name: AMQP_PASSWORD
              value: changeme
          image: docker.io/g1raffi/amqp-consumer:latest
          imagePullPolicy: Always
          name: amqp-consumer
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      restartPolicy: Always
